'use strict';

/**
 * Application-wide constants.
 * Centralised here so they can be changed in one place.
 */

// User roles
const ROLES = Object.freeze({
  ADMIN: 'ADMIN',
  HOSPITAL: 'HOSPITAL',
  BLOOD_BANK: 'BLOOD_BANK',
  DONOR: 'DONOR',
});

// Organisation statuses
const ORG_STATUS = Object.freeze({
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED',
});

// User/account statuses
const USER_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
});

// Blood types
const BLOOD_TYPES = Object.freeze([
  'A+', 'A-',
  'B+', 'B-',
  'AB+', 'AB-',
  'O+', 'O-',
]);

// Emergency request statuses
const REQUEST_STATUS = Object.freeze({
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  IN_TRANSIT: 'IN_TRANSIT',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
});

// Valid request status transitions
// Key = current status, Value = allowed next statuses
const REQUEST_TRANSITIONS = Object.freeze({
  PENDING: ['APPROVED', 'REJECTED', 'CANCELLED'],
  APPROVED: ['IN_TRANSIT', 'CANCELLED'],
  REJECTED: [],
  IN_TRANSIT: ['COMPLETED'],
  COMPLETED: [],
  CANCELLED: [],
});

// Donation request statuses
const DONATION_REQUEST_STATUS = Object.freeze({
  OPEN: 'OPEN',
  FULFILLED: 'FULFILLED',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED',
});

// Donor response statuses
const DONOR_RESPONSE_STATUS = Object.freeze({
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  DECLINED: 'DECLINED',
  COMPLETED: 'COMPLETED',
});

// Notification channels
const NOTIFICATION_CHANNELS = Object.freeze({
  SMS: 'SMS',
  WHATSAPP: 'WHATSAPP',
  EMAIL: 'EMAIL',
  VOICE: 'VOICE',
  IN_APP: 'IN_APP',
});

// Notification statuses
const NOTIFICATION_STATUS = Object.freeze({
  PENDING: 'PENDING',
  SENT: 'SENT',
  DELIVERED: 'DELIVERED',
  FAILED: 'FAILED',
  RETRYING: 'RETRYING',
});

// OTP purposes
const OTP_PURPOSE = Object.freeze({
  EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
  PHONE_VERIFICATION: 'PHONE_VERIFICATION',
  PASSWORD_RESET: 'PASSWORD_RESET',
  LOGIN_2FA: 'LOGIN_2FA',
});

// Subscription statuses
const SUBSCRIPTION_STATUS = Object.freeze({
  TRIAL: 'TRIAL',
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED',
  PAST_DUE: 'PAST_DUE',
});

// Payment statuses
const PAYMENT_STATUS = Object.freeze({
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
});

// Audit event types
const AUDIT_EVENTS = Object.freeze({
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_STATUS_CHANGED: 'USER_STATUS_CHANGED',
  PASSWORD_RESET: 'PASSWORD_RESET',
  OTP_SENT: 'OTP_SENT',
  OTP_VERIFIED: 'OTP_VERIFIED',
  ORG_REGISTERED: 'ORG_REGISTERED',
  ORG_VERIFIED: 'ORG_VERIFIED',
  ORG_REJECTED: 'ORG_REJECTED',
  ORG_SUSPENDED: 'ORG_SUSPENDED',
  INVENTORY_CREATED: 'INVENTORY_CREATED',
  INVENTORY_UPDATED: 'INVENTORY_UPDATED',
  INVENTORY_DELETED: 'INVENTORY_DELETED',
  REQUEST_CREATED: 'REQUEST_CREATED',
  REQUEST_STATUS_CHANGED: 'REQUEST_STATUS_CHANGED',
  DONATION_REQUEST_CREATED: 'DONATION_REQUEST_CREATED',
  DONATION_REQUEST_CLOSED: 'DONATION_REQUEST_CLOSED',
  DONOR_RESPONDED: 'DONOR_RESPONDED',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  SUBSCRIPTION_ACTIVATED: 'SUBSCRIPTION_ACTIVATED',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  LOW_STOCK_ALERT: 'LOW_STOCK_ALERT',
  NOTIFICATION_SENT: 'NOTIFICATION_SENT',
});

// Default pagination
const PAGINATION = Object.freeze({
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
});

// Gender options
const GENDERS = Object.freeze(['MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY']);

// Hospital types
const HOSPITAL_TYPES = Object.freeze([
  'GENERAL',
  'SPECIALIST',
  'TEACHING',
  'PRIMARY_HEALTH_CENTRE',
  'CLINIC',
  'PRIVATE',
  'OTHER',
]);

// Ownership types
const OWNERSHIP_TYPES = Object.freeze([
  'GOVERNMENT',
  'PRIVATE',
  'FAITH_BASED',
  'NGO',
  'OTHER',
]);

module.exports = {
  ROLES,
  ORG_STATUS,
  USER_STATUS,
  BLOOD_TYPES,
  REQUEST_STATUS,
  REQUEST_TRANSITIONS,
  DONATION_REQUEST_STATUS,
  DONOR_RESPONSE_STATUS,
  NOTIFICATION_CHANNELS,
  NOTIFICATION_STATUS,
  OTP_PURPOSE,
  SUBSCRIPTION_STATUS,
  PAYMENT_STATUS,
  AUDIT_EVENTS,
  PAGINATION,
  GENDERS,
  HOSPITAL_TYPES,
  OWNERSHIP_TYPES,
};
